//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 11:50:06 PM CDT 
//

package com.safee.jaxbclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Student complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Student"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="studentId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="marks" type="{http://www.example.org/Student}marks"/&gt;
 *         &lt;element name="addresses" type="{http://www.example.org/Student}addresses"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Student", propOrder = { "studentId", "firstName", "lastName", "marks", "addresses" })
@XmlRootElement
public class Student {

	protected int studentId;
	@XmlElement(required = true)
	protected String firstName;
	@XmlElement(required = true)
	protected String lastName;
	@XmlElement(required = true)
	protected Marks marks;
	@XmlElement(required = true)
	protected Addresses addresses;

	/**
	 * Gets the value of the studentId property.
	 * 
	 */
	public int getStudentId() {
		return studentId;
	}

	/**
	 * Sets the value of the studentId property.
	 * 
	 */
	public void setStudentId(int value) {
		this.studentId = value;
	}

	/**
	 * Gets the value of the firstName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFirstName() {
		return firstName;
	}

	/**
	 * Sets the value of the firstName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFirstName(String value) {
		this.firstName = value;
	}

	/**
	 * Gets the value of the lastName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLastName() {
		return lastName;
	}

	/**
	 * Sets the value of the lastName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLastName(String value) {
		this.lastName = value;
	}

	/**
	 * Gets the value of the marks property.
	 * 
	 * @return possible object is {@link Marks }
	 * 
	 */
	public Marks getMarks() {
		return marks;
	}

	/**
	 * Sets the value of the marks property.
	 * 
	 * @param value
	 *            allowed object is {@link Marks }
	 * 
	 */
	public void setMarks(Marks value) {
		this.marks = value;
	}

	/**
	 * Gets the value of the addresses property.
	 * 
	 * @return possible object is {@link Addresses }
	 * 
	 */
	public Addresses getAddresses() {
		return addresses;
	}

	/**
	 * Sets the value of the addresses property.
	 * 
	 * @param value
	 *            allowed object is {@link Addresses }
	 * 
	 */
	public void setAddresses(Addresses value) {
		this.addresses = value;
	}

}
